version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: chat_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: satudua
      POSTGRES_DB: chat_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: chat_app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
