// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"github.com/robfig/cron/v3"
	"gorm.io/gorm"
	"main/config"
	"main/handlers"
	"main/repository"
	"main/router"
	"main/scheduler"
	"main/services"
	"main/websocket"
)

// Injectors from wire.go:

// InitializeApp sekarang mengembalikan struct Application dan error
func InitializeApp(cfg *config.Config, db *gorm.DB) (*Application, error) {
	aiService, err := services.ProvideAIService(cfg)
	if err != nil {
		return nil, err
	}
	sessionRepository := repository.NewSessionRepository(db)
	sessionService := services.NewSessionService(sessionRepository)
	hub := websocket.NewHub(aiService, sessionService)
	userRepository := repository.NewUserRepository(db)
	chatRepository := repository.NewChatRepository(db)
	roomRepository := repository.NewRoomRepository(db)
	uploadService := services.NewUploadService(cfg)
	roomService := services.NewRoomService(roomRepository, userRepository, uploadService)
	chatHandler := handlers.NewChatHandler(hub, userRepository, chatRepository, roomService)
	tokenRepository := repository.NewTokenRepository(db)
	jwtService := services.NewJWTService(cfg)
	authService := services.NewAuthService(userRepository, tokenRepository, jwtService)
	authHandler := handlers.NewAuthHandler(authService)
	userService := services.NewUserService(userRepository, uploadService)
	userHandler := handlers.NewUserHandler(userService)
	roomHandler := handlers.NewRoomHandler(roomService)
	uploadHandler := handlers.NewUploadHandler(uploadService)
	productHandler := handlers.NewProductHandler()
	aiHandler := handlers.NewAIHandler(aiService, sessionService)
	app := router.NewRouter(chatHandler, authHandler, userHandler, roomHandler, uploadHandler, productHandler, aiHandler, tokenRepository, cfg)
	cron := scheduler.InitCronJobs(tokenRepository)
	application := NewApplication(app, cron)
	return application, nil
}

// wire.go:

// Definisikan struct untuk menampung hasil inisialisasi
type Application struct {
	App  *fiber.App
	Cron *cron.Cron
}

// Buat provider untuk struct Application
func NewApplication(app *fiber.App, cron2 *cron.Cron) *Application {
	return &Application{App: app, Cron: cron2}
}

var websocketSet = wire.NewSet(websocket.NewHub)

var repositorySet = wire.NewSet(repository.NewUserRepository, repository.NewTokenRepository, repository.NewRoomRepository, repository.NewChatRepository, repository.NewSessionRepository)

var serviceSet = wire.NewSet(services.NewJWTService, services.NewAuthService, services.NewUserService, services.NewRoomService, services.NewUploadService, services.NewSessionService, services.ProvideAIService)

var handlerSet = wire.NewSet(handlers.NewAuthHandler, handlers.NewChatHandler, handlers.NewUserHandler, handlers.NewRoomHandler, handlers.NewUploadHandler, handlers.NewProductHandler, handlers.NewAIHandler)

var schedulerSet = wire.NewSet(scheduler.InitCronJobs)
